### ISSUE TITLE
SEO: GoogleAnalytics Account info@fly-tirol.com

### ISSUE THREAD

**Issue by naschidaniel** [naschidaniel/fly-tirol#44]

**Comment by Kilianflytirol** [comment]
G-BWWL6CCGY2 Google Analytics Mess-ID für info@fly-tirol.com

**Comment by Kilianflytirol** [comment]
G-VX34DRY353 Google Analytics Mess-ID für info@fly-tirol.com

**Comment by naschidaniel** [comment]
@Kilianflytirol,
ich benötige die Tracking-ID sie startet mit 'UA-XXX-X'. Kannst du mir diese zukommen lassen?

https://support.google.com/analytics/answer/7372977?hl=de

Verwendetes Paket: https://google-analytics.nuxtjs.org/options

**Comment by naschidaniel** [comment]
@Kilianflytirol, thank you.
I will solve #45  soon.
