### ISSUE TITLE
Chore: Do not show past events

### ISSUE THREAD

**Issue by naschidaniel** [naschidaniel/fly-tirol#85]
@Kilianflytirol, 

Can past dates be hidden in Shopify or should I not display them on the website anymore?

Example:
![grafik](https://user-images.githubusercontent.com/6561161/132398980-fc3581fc-2596-4511-8f2c-1dea05c5204e.png)

**Comment by Kilianflytirol** [comment]
Hi Dani,

Ich kann die past dates auch bei shopify rausnehmen. 

Von meinem iPhone gesendet

**Comment by naschidaniel** [comment]
Kurse älter als 14 Tage werden nicht mehr angezeigt.
https://github.com/naschidaniel/fly-tirol/commit/188c4140ef1fc2a8f1cfff38956d7070ef7e5bde
